### ISSUE TITLE
doplnit TVY

### ISSUE THREAD

**Issue by pkabelka** [pkabelka/skola#2]
je potřeba dopsat USB a základní desku

![01-usb](https://user-images.githubusercontent.com/26080087/51935320-eeb84180-2405-11e9-8e88-a0c9ffd9962e.jpg)
![02-usb](https://user-images.githubusercontent.com/26080087/51935322-eeb84180-2405-11e9-8426-51f9113e5d3c.jpg)
![03-motherboard](https://user-images.githubusercontent.com/26080087/51935323-eeb84180-2405-11e9-9526-5eecf6e02e51.jpg)
![04-motherboard](https://user-images.githubusercontent.com/26080087/51935324-ef50d800-2405-11e9-967f-98973fb99553.jpg)

**Comment by vojtas131** [comment]
#3 Done ni🅱🅱a
